<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="11" hostname="DSR" failures="1" tests="1" name="Default test" time="11.236" errors="0" timestamp="2025-03-24T23:28:35 IST">
  <testcase classname="test.UsersTest" name="verifyUsersModuleFooterSection" time="0.137">
    <failure type="java.lang.AssertionError" message="expected [© 2025, Eseal.ioo] but found [© 2025, Eseal.io]">
      <![CDATA[java.lang.AssertionError: expected [© 2025, Eseal.ioo] but found [© 2025, Eseal.io]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at test.UsersTest.verifyUsersModuleFooterSection(UsersTest.java:78)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyUsersModuleFooterSection -->
  <testcase classname="test.UsersTest" name="verifySearchUser" time="0.0">
    <ignored/>
  </testcase> <!-- verifySearchUser -->
  <testcase classname="test.UsersTest" name="verifyMandatoryFieldValidationForUpdatePassword" time="0.0">
    <ignored/>
  </testcase> <!-- verifyMandatoryFieldValidationForUpdatePassword -->
  <testcase classname="test.UsersTest" name="verifySavedUserDetailsInEditWindow" time="0.0">
    <ignored/>
  </testcase> <!-- verifySavedUserDetailsInEditWindow -->
  <testcase classname="test.UsersTest" name="verifyNavigationToUsersModule" time="0.0">
    <ignored/>
  </testcase> <!-- verifyNavigationToUsersModule -->
  <testcase classname="test.UsersTest" name="verifyDeleteUser" time="0.0">
    <ignored/>
  </testcase> <!-- verifyDeleteUser -->
  <testcase classname="test.UsersTest" name="verifyAddUserWithValidDetails" time="0.0">
    <ignored/>
  </testcase> <!-- verifyAddUserWithValidDetails -->
  <testcase classname="test.UsersTest" name="verifyUsersModuleDetails" time="0.0">
    <ignored/>
  </testcase> <!-- verifyUsersModuleDetails -->
  <testcase classname="test.UsersTest" name="verifyMandatoryFieldAlertsInAddUser" time="0.0">
    <ignored/>
  </testcase> <!-- verifyMandatoryFieldAlertsInAddUser -->
  <testcase classname="test.UsersTest" name="verifyAddUserWithDuplicateUserName" time="0.0">
    <ignored/>
  </testcase> <!-- verifyAddUserWithDuplicateUserName -->
  <testcase classname="test.UsersTest" name="verifyUserInUsersModuleGridWithPagination" time="0.0">
    <ignored/>
  </testcase> <!-- verifyUserInUsersModuleGridWithPagination -->
  <testcase classname="test.UsersTest" name="verifyAddUserUsingLeadingAndTrailingSpaces" time="0.0">
    <ignored/>
  </testcase> <!-- verifyAddUserUsingLeadingAndTrailingSpaces -->
</testsuite> <!-- Default test -->
