<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DSR" failures="13" tests="35" name="Test" time="4716.755" errors="0" timestamp="2025-03-19T22:03:27 IST">
  <testcase classname="test.TransactionsTest" name="verifyNavigationToUsersModule" time="0.759"/>
  <testcase classname="test.TransactionsTest" name="verifyAddTransactionWithValidData" time="3.485">
    <failure type="java.lang.AssertionError" message="expected [Successfully submitted!] but found [Feature Code already exists]">
      <![CDATA[java.lang.AssertionError: expected [Successfully submitted!] but found [Feature Code already exists]
at test.TransactionsTest.verifyAddTransactionWithValidData(TransactionsTest.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyAddTransactionWithValidData -->
  <testcase classname="test.TransactionsTest" name="verifyAddUserWithDuplicateTransactionName" time="4.093">
    <failure type="java.lang.AssertionError" message="expected [Transaction name is already exists] but found [Transaction Name already exists]">
      <![CDATA[java.lang.AssertionError: expected [Transaction name is already exists] but found [Transaction Name already exists]
at test.TransactionsTest.verifyAddUserWithDuplicateTransactionName(TransactionsTest.java:86)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyAddUserWithDuplicateTransactionName -->
  <testcase classname="test.TransactionsTest" name="verifyAddUserWithDuplicateFeatureCode" time="4.003"/>
  <testcase classname="test.TransactionsTest" name="verifyMandatoryFieldValidationForAddUser" time="2.197"/>
  <testcase classname="test.TransactionsTest" name="verifyAddUserUsingLeadingAndTrailingSpaces" time="3.121">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Testabc] but found [ Testabc ]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Testabc] but found [ Testabc ]
at test.TransactionsTest.verifyAddUserUsingLeadingAndTrailingSpaces(TransactionsTest.java:151)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- verifyAddUserUsingLeadingAndTrailingSpaces -->
  <testcase classname="test.TransactionsTest" name="verifySavedTransactionDetailsInEditWindow" time="187.762">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [1] but found [null],
	expected [0] but found [null],
	expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [1] but found [null],
expected [0] but found [null],
expected [0] but found [null]
at test.TransactionsTest.verifySavedTransactionDetailsInEditWindow(TransactionsTest.java:177)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- verifySavedTransactionDetailsInEditWindow -->
  <testcase classname="test.TransactionsTest" name="verifyUserInUsersModuleGridWithPagination" time="187.689"/>
  <testcase classname="test.TransactionsTest" name="verifyDeleteUser" time="189.122"/>
  <testcase classname="test.UsersTest" name="verifyDeleteUser" time="439.506"/>
  <testcase classname="test.UsersTest" name="verifyNavigationToUsersModule" time="1.424"/>
  <testcase classname="test.UsersTest" name="verifyAddUserWithValidDetails" time="3.66">
    <failure type="java.lang.AssertionError" message="expected [Successfully submitted!] but found [User name is already exists]">
      <![CDATA[java.lang.AssertionError: expected [Successfully submitted!] but found [User name is already exists]
at test.UsersTest.verifyAddUserWithValidDetails(UsersTest.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyAddUserWithValidDetails -->
  <testcase classname="test.UsersTest" name="verifyMandatoryFieldValidationForAddUser" time="2.09"/>
  <testcase classname="test.UsersTest" name="verifyMandatoryFieldValidationForUpdatePassword" time="435.82">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.UsersTest.verifyMandatoryFieldValidationForUpdatePassword(UsersTest.java:135)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyMandatoryFieldValidationForUpdatePassword -->
  <testcase classname="test.UsersTest" name="verifyAddUserUsingLeadingAndTrailingSpaces" time="3.062">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [atbs] but found [  atbs  ]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [atbs] but found [  atbs  ]
at test.UsersTest.verifyAddUserUsingLeadingAndTrailingSpaces(UsersTest.java:168)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- verifyAddUserUsingLeadingAndTrailingSpaces -->
  <testcase classname="test.UsersTest" name="verifySearchUser" time="0.002"/>
  <testcase classname="test.UsersTest" name="verifySavedUserDetailsInEditWindow" time="426.887">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Plant] but found [null],
	expected [VCPL - Panthnagar] but found [null],
	expected [None] but found [null],
	expected [Testing role] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Plant] but found [null],
expected [VCPL - Panthnagar] but found [null],
expected [None] but found [null],
expected [Testing role] but found [null]
at test.UsersTest.verifySavedUserDetailsInEditWindow(UsersTest.java:207)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- verifySavedUserDetailsInEditWindow -->
  <testcase classname="test.UsersTest" name="verifyUserInUsersModuleGridWithPagination" time="397.959"/>
  <testcase classname="test.LoginTest" name="verifyLoginPageTitleAndUrl" time="0.015"/>
  <testcase classname="test.LoginTest" name="verifyFieldAndCheckboxLabels" time="0.109"/>
  <testcase classname="test.LoginTest" name="verifyLoginUsingValidCredentials" time="1.036"/>
  <testcase classname="test.LoginTest" name="verifyLoginUsingInvalidCredentials" time="1.365"/>
  <testcase classname="test.LoginTest" name="verifyLoginWithInvalidEmailAndValidPassword" time="11.439"/>
  <testcase classname="test.LoginTest" name="verifyLoginWithValidEmailAndInvalidPassword" time="10.971"/>
  <testcase classname="test.LoginTest" name="verifyLoginWithBlankCredentials" time="0.414"/>
  <testcase classname="test.LoginTest" name="verifyLoginWithEmailOnly" time="0.35"/>
  <testcase classname="test.LoginTest" name="verifyLoginWithPasswordOnly" time="0.326"/>
  <testcase classname="test.LoginTest" name="verifyLoginWithShortPassword" time="0.469"/>
  <testcase classname="test.LoginTest" name="verifyLoginWithUppercaseInsensitiveEmail" time="0.929"/>
  <testcase classname="test.LoginTest" name="verifyLoginWithLowercaseInsensitiveEmail" time="0.923"/>
  <testcase classname="test.LogoutTest" name="verifyLogoutFromLogoutOptionUnderProfile" time="1.092">
    <failure type="java.lang.AssertionError" message="expected [null] but found [https://vguard-bt-stg.esealcom.com/login]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [https://vguard-bt-stg.esealcom.com/login]
at test.LogoutTest.verifyLogoutFromLogoutOptionUnderProfile(LogoutTest.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyLogoutFromLogoutOptionUnderProfile -->
  <testcase classname="test.LogoutTest" name="verifyReLoginImmediatelyAfterLogout" time="1.099">
    <failure type="java.lang.AssertionError" message="expected [null] but found [https://vguard-bt-stg.esealcom.com/login]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [https://vguard-bt-stg.esealcom.com/login]
at test.LogoutTest.verifyReLoginImmediatelyAfterLogout(LogoutTest.java:54)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyReLoginImmediatelyAfterLogout -->
  <testcase classname="test.LogoutTest" name="verifyLogoutAndBackNavigation" time="1.096">
    <failure type="java.lang.AssertionError" message="expected [null] but found [https://vguard-bt-stg.esealcom.com/login]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [https://vguard-bt-stg.esealcom.com/login]
at test.LogoutTest.verifyLogoutAndBackNavigation(LogoutTest.java:74)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyLogoutAndBackNavigation -->
  <testcase classname="test.LogoutTest" name="verifyLogoutAndForwardNavigation" time="1.09">
    <failure type="java.lang.AssertionError" message="expected [null] but found [https://vguard-bt-stg.esealcom.com/login]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [https://vguard-bt-stg.esealcom.com/login]
at test.LogoutTest.verifyLogoutAndForwardNavigation(LogoutTest.java:87)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyLogoutAndForwardNavigation -->
  <testcase classname="test.LogoutTest" name="verifyAutoLogoutAfterSessionTimeout" time="90.42">
    <failure type="java.lang.AssertionError" message="expected [null] but found [https://vguard-bt-stg.esealcom.com/admin/home]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [https://vguard-bt-stg.esealcom.com/admin/home]
at test.LogoutTest.verifyAutoLogoutAfterSessionTimeout(LogoutTest.java:94)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyAutoLogoutAfterSessionTimeout -->
</testsuite> <!-- Test -->
